language: c

os: osx

env:
   global:
     - CRAN: "http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-vignettes --no-manual --no-examples"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true"

script: ./travis-tool.sh run_tests

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh github_package USGS-R/EflowStats@v4.1.1

after_failure:
  ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
